CREATE TABLE users (
    id UUID NOT NULL DEFAULT gen_random_uuid(), full_name VARCHAR(120) NOT NULL,
    email VARCHAR(180) NOT NULL, password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL DEFAULT 'USER', active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL,
    CONSTRAINT pk_users PRIMARY KEY (id), CONSTRAINT uk_users_email UNIQUE (email)
);
